export const _Channels = 'Favorite Channels'
export const _OtherChannels = 'Other Channels'



const currentUser = [{
    "additionalUserInfo": {
        "isNewUser": false,
        "providerId": "password",
    },
    "credential": null,
    "operationType": "signIn",
    "user": {
        "apiKey": "AIzaSyDkm9W_7FOkWziBaNi7jJdiuXpqkL-EdHE",
        "appName": "[DEFAULT]",
        "authDomain": "my-test-4ef11.firebaseapp.com",
        "createdAt": "1535600369000",
        "displayName": "August",
        "email": "phuong.august@gmail.com",
        "emailVerified": false,
        "isAnonymous": false,
        "lastLoginAt": "1536921695000",
        "phoneNumber": null,
        "photoURL": null,
        "providerData": [
            {
                "displayName": "August",
                "email": "phuong.august@gmail.com",
                "phoneNumber": null,
                "photoURL": null,
                "providerId": "password",
                "uid": "phuong.august@gmail.com",
            },
        ],
        "redirectEventId": null,
        "stsTokenManager": {
            "accessToken": "eyJhbGciOiJSUzI1NiIsImtpZCI6IjBmNTVkZWZlOWU5YzU2ZmRhZTRkOGY0MDFjZjQ5Njc4YzE2N2MzYWEifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vbXktdGVzdC00ZWYxMSIsIm5hbWUiOiJBdWd1c3QiLCJhdWQiOiJteS10ZXN0LTRlZjExIiwiYXV0aF90aW1lIjoxNTM2OTIxNjk1LCJ1c2VyX2lkIjoia0lIQXBkWXBsTVFtSkdqTE9ORXlDTm5vNGNQMiIsInN1YiI6ImtJSEFwZFlwbE1RbUpHakxPTkV5Q05ubzRjUDIiLCJpYXQiOjE1MzY5MjE2OTUsImV4cCI6MTUzNjkyNTI5NSwiZW1haWwiOiJwaHVvbmcuYXVndXN0QGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJwaHVvbmcuYXVndXN0QGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.VDr45cKbA58wuKZ8X3Igq6ItqgsABDwxCrGR6MqHzk0ofDRpIO8zjjnf5OY7YN1dn2tzz6HEg8IG87xYW5HiBPbsA9gvJiHQZkQfaBFrWQ18c2zMm_pLZW8tTq6h8yDaEF-TqGox7N8NZsXu2Br4zax9h8swqPW-QpJ3ye1rWM3LSWXYUcR1nR5ME8iwKeGmkp5xoFXwvI1FOH8leTkkb71iV07FfyqMUuaZHYFex1IZLq9lLXWYhyVl3kDP9YPDgqPVF7HlrknYHR1Zp7_yKsp1NtbhNokA7Q5lrjMpCmsF3ABUwrIln6wP6_HEjPoN_u3nBRt27onZIE1YrJI7Iw",
            "apiKey": "AIzaSyDkm9W_7FOkWziBaNi7jJdiuXpqkL-EdHE",
            "expirationTime": 1536925295705,
            "refreshToken": "AEXAG-c7DUSfs5J82k0dzcJk0U8L5_XRGnjVgFXzdl_38a8u__qYChFjGOJOs2VbaEo-nXOh742mzc_mA9VA4YB-BdcRnIdmtJG-zDCpZ206IN-uHsLVy5qSIyV6WS758pYG0pedrbRHndL97hMV4n5a_VtnLNQN2RhieRJL9FlKw0L7ZY1Bji90wTpNm4noCoNwgVBE1uPwQ4w-mscldTw2hYeP1htfDdfESGs_n-cmdH6CcJZdr0k",
        },
        "uid": "kIHApdYplMQmJGjLONEyCNno4cP2",
    },
},
{
    "_update": ['Function anonymous'],
    "_updateMetaData": ['Function anonymous'],
    "connectionStatus": "nonavailable",
    "createMetaData": ['Function anonymous'],
    "deleteAllMetaData": ['Function anonymous'],
    "deleteMetaData": ['Function anonymous'],
    "friendDiscoveryKey": null,
    "friendName": null,
    "getOriginalProfileUrl": ['Function anonymous'],
    "isActive": true,
    "lastSeenAt": 0,
    "metaData": {},
    "nickname": "Abctest",
    "profileUrl": "https://sendbird.com/main/img/profiles/profile_25_512px.png",
    "serialize": ['Function anonymous'],
    "updateMetaData": ['Function anonymous'],
    "userId": "jXXwmms9e7UbrwayWrcPwVqyhIN2",
}
]


// var docData = {
//   uid: null,
//   email: null,
//   username: null,
//   firstname: null,
//   lastname: null,
//   phoneNumber: null,
//   photoURL: null,
//   displayName: null,
//   postalcode: null,
//   birthday: null,

//   conditions: true,
//   showUsername: true,
//   isNaturopath: false,
// };

var currentUser2 = {
    "apiKey": "AIzaSyDkm9W_7FOkWziBaNi7jJdiuXpqkL-EdHE",
    "appName": "[DEFAULT]",
    "authDomain": "my-test-4ef11.firebaseapp.com",
    "createdAt": "1535600369000",
    "displayName": "August",
    "email": "phuong.august@gmail.com",
    "emailVerified": false,
    "isAnonymous": false,
    "lastLoginAt": "1536832005000",
    "phoneNumber": null,
    "photoURL": null,
    "providerData": [
        {
            "displayName": "August",
            "email": "phuong.august@gmail.com",
            "phoneNumber": null,
            "photoURL": null,
            "providerId": "password",
            "uid": "phuong.august@gmail.com",
        },
    ],
    "redirectEventId": null,
    "stsTokenManager": {
        "accessToken": "eyJhbGciOiJSUzI1NiIsImtpZCI6IjBmNTVkZWZlOWU5YzU2ZmRhZTRkOGY0MDFjZjQ5Njc4YzE2N2MzYWEifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vbXktdGVzdC00ZWYxMSIsIm5hbWUiOiJBdWd1c3QiLCJhdWQiOiJteS10ZXN0LTRlZjExIiwiYXV0aF90aW1lIjoxNTM2ODMxMzQxLCJ1c2VyX2lkIjoia0lIQXBkWXBsTVFtSkdqTE9ORXlDTm5vNGNQMiIsInN1YiI6ImtJSEFwZFlwbE1RbUpHakxPTkV5Q05ubzRjUDIiLCJpYXQiOjE1MzY4OTkxODIsImV4cCI6MTUzNjkwMjc4MiwiZW1haWwiOiJwaHVvbmcuYXVndXN0QGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJwaHVvbmcuYXVndXN0QGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.I9Ihk2ShMrpNJ7NFvBOMPMHaQTn3lxK0bUSBW_lOo8LwDDVo8A_KEFoQVxYpiqiIKZmkVYVIKt3ajJDwl6GAOFr9Md0Pm8hd6-L1lqf0CGHWxkRJyECJlS22U9TkEQ6SjqlInHdVT0EcZfX75bzGrdDfkPyhQypWZ_RHIavrkOdSjq1HNDLtxXXSTXD2ide4_rHP8q4a1rlhzNtUnvyKyNa7c9yGklmKZJqaCrRRABP1486FvYQj8y6uNTv0FR2grrWiBkFSdWTtJobXpf2mbzwzHXXhBxculIXHEy3agnbkrmY_XQDMZaQBEqo1xk2lylHFflfyANyUXupX6OAtRw",
        "apiKey": "AIzaSyDkm9W_7FOkWziBaNi7jJdiuXpqkL-EdHE",
        "expirationTime": 1536902780060,
        "refreshToken": "AEXAG-cxLowiITvaKYbhybwgvPyZ9ZLuVmyDulZsbcxZxYl2d90kvOghsyT61MszeyiemnXV3rXTJ6H3u7mXKrQH5KOXk_b74YlFKr5QuSR1iG_aO_hPKrm47_d-znSZw0oUDXqJ_HKuXgf3BTR1VNVA0XbNFVRjQgc3p4Jg5d2LrLKfFDuZuPAiawJmf2nwB4h717PYIoDjcvVPtGK4EMlLhEKV8Mkk9iqF8GLG1JbrRhMsCCNYRzM",
    },
    "uid": "kIHApdYplMQmJGjLONEyCNno4cP2",
}
var WQ8pEDSIxPUUCwoWwv5nd8ITerx1 = {
    "conditions": true,
    "showUsername": true,
    "isNaturopath": false,
    "username": "phuonghuynh",
    "firstname": "phuong",
    "lastname": "huynh",
    "phoneNumber": "+84906589850",
    "photoURL": null,
    "birthday": {
        "nanoseconds": 0,
        "seconds": 651517200,
    },
    "postalcode": 3.14159265,


    stringExample: "Hello world!",
    numberExample: 3.14159265,
    dateExample: new Date("December 10, 1815"),
    arrayExample: [5, true, "hello"],
    nullExample: null,
    objectExample: {
        a: 5,
        b: {
            nested: "foo"
        }
    }
}



const clubflora = {
    "_sendMarkAsRead": ['Function anonymous'],
    "acceptInvitation": ['Function anonymous'],
    "addMember": ['Function anonymous'],
    "banUser": ['Function anonymous'],
    "banUserWithUserId": ['Function anonymous'],
    "cachedReadReceiptStatus": {
        "WQ8pEDSIxPUUCwoWwv5nd8ITerx1": 0,
        "jXXwmms9e7UbrwayWrcPwVqyhIN2": 0,
        "x2Z949IXlDMRI6frLlGMg3W8owr2": 0,
    },
    "channelType": "group",
    "coverUrl": "https://sendbird.com/main/img/cover/cover_07.jpg",
    "createBannedUserListQuery": ['Function anonymous'],
    "createMemberListQuery": ['Function anonymous'],
    "createdAt": 1537157949000,
    "customType": "",
    "data": "",
    "declineInvitation": ['Function anonymous'],
    "endTyping": ['Function anonymous'],
    "fileUploadRequest": {},
    "freeze": ['Function anonymous'],
    "getPushPreference": ['Function anonymous'],
    "getReadReceipt": ['Function anonymous'],
    "getReadStatus": ['Function anonymous'],
    "getTypingMembers": ['Function anonymous'],
    "hide": ['Function anonymous'],
    "invalidateTypingStatus": ['Function anonymous'],
    "invite": ['Function anonymous'],
    "inviteWithUserIds": ['Function anonymous'],
    "invitedAt": 1537157949135,
    "inviter": {
        "_update": ['Function anonymous'],
        "_updateMetaData": ['Function anonymous'],
        "connectionStatus": "nonavailable",
        "createMetaData": ['Function anonymous'],
        "deleteAllMetaData": ['Function anonymous'],
        "deleteMetaData": ['Function anonymous'],
        "friendDiscoveryKey": null,
        "friendName": null,
        "getOriginalProfileUrl": ['Function anonymous'],
        "isActive": true,
        "lastSeenAt": 0,
        "metaData": {},
        "nickname": "Abctest",
        "profileUrl": "https://sendbird.com/main/img/profiles/profile_25_512px.png",
        "serialize": ['Function anonymous'],
        "updateMetaData": ['Function anonymous'],
        "userId": "jXXwmms9e7UbrwayWrcPwVqyhIN2",
    },
    "isDistinct": false,
    "isEphemeral": false,
    "isFrozen": false,
    "isHidden": false,
    "isPublic": false,
    "isPushEnabled": true,
    "isSuper": false,
    "isTyping": ['Function anonymous'],
    "join": ['Function anonymous'],
    "joinedMemberCount": 3,
    "lastMessage": null,
    "leave": ['Function anonymous'],
    "markAsRead": ['Function anonymous'],
    "memberCount": 3,
    "memberMap": {
        "WQ8pEDSIxPUUCwoWwv5nd8ITerx1": {
            "connectionStatus": "offline",
            "friendDiscoveryKey": null,
            "friendName": null,
            "isActive": true,
            "isBlockedByMe": false,
            "isBlockingMe": false,
            "lastSeenAt": 1537153283116,
            "metaData": {},
            "nickname": "Phuong Huynh",
            "parse": ['Function anonymous'],
            "profileUrl": "https://sendbird.com/main/img/profiles/profile_37_512px.png",
            "state": "joined",
            "userId": "WQ8pEDSIxPUUCwoWwv5nd8ITerx1",
        },
        "jXXwmms9e7UbrwayWrcPwVqyhIN2": {
            "connectionStatus": "online",
            "friendDiscoveryKey": null,
            "friendName": null,
            "isActive": true,
            "isBlockedByMe": false,
            "isBlockingMe": false,
            "lastSeenAt": 0,
            "metaData": {},
            "nickname": "Abctest",
            "parse": ['Function anonymous'],
            "profileUrl": "https://sendbird.com/main/img/profiles/profile_25_512px.png",
            "state": "joined",
            "userId": "jXXwmms9e7UbrwayWrcPwVqyhIN2",
        },
        "x2Z949IXlDMRI6frLlGMg3W8owr2": {
            "connectionStatus": "online",
            "friendDiscoveryKey": null,
            "friendName": null,
            "isActive": true,
            "isBlockedByMe": false,
            "isBlockingMe": false,
            "lastSeenAt": 0,
            "metaData": {},
            "nickname": "PhuongAmagumo",
            "parse": ['Function anonymous'],
            "profileUrl": "https://sendbird.com/main/img/profiles/profile_14_512px.png",
            "state": "joined",
            "userId": "x2Z949IXlDMRI6frLlGMg3W8owr2",
        },
    },
    "members": [
        {
            "connectionStatus": "offline",
            "friendDiscoveryKey": null,
            "friendName": null,
            "isActive": true,
            "isBlockedByMe": false,
            "isBlockingMe": false,
            "lastSeenAt": 1537153283116,
            "metaData": {},
            "nickname": "Phuong Huynh",
            "parse": ['Function anonymous'],
            "profileUrl": "https://sendbird.com/main/img/profiles/profile_37_512px.png",
            "state": "joined",
            "userId": "WQ8pEDSIxPUUCwoWwv5nd8ITerx1",
        },
        {
            "connectionStatus": "online",
            "friendDiscoveryKey": null,
            "friendName": null,
            "isActive": true,
            "isBlockedByMe": false,
            "isBlockingMe": false,
            "lastSeenAt": 0,
            "metaData": {},
            "nickname": "PhuongAmagumo",
            "parse": ['Function anonymous'],
            "profileUrl": "https://sendbird.com/main/img/profiles/profile_14_512px.png",
            "state": "joined",
            "userId": "x2Z949IXlDMRI6frLlGMg3W8owr2",
        },
        {
            "connectionStatus": "online",
            "friendDiscoveryKey": null,
            "friendName": null,
            "isActive": true,
            "isBlockedByMe": false,
            "isBlockingMe": false,
            "lastSeenAt": 0,
            "metaData": {},
            "nickname": "Abctest",
            "parse": ['Function anonymous'],
            "profileUrl": "https://sendbird.com/main/img/profiles/profile_25_512px.png",
            "state": "joined",
            "userId": "jXXwmms9e7UbrwayWrcPwVqyhIN2",
        },
    ],
    "muteUser": ['Function anonymous'],
    "muteUserWithUserId": ['Function anonymous'],
    "myCountPreference": "all",
    "myMemberState": "joined",
    "myMutedState": "unmuted",
    "myRole": "none",
    "name": "Club Flora",
    "parse": ['Function anonymous'],
    "refresh": ['Function anonymous'],
    "removeMember": ['Function anonymous'],
    "resetMyHistory": ['Function anonymous'],
    "setLatestMemberCount": ['Function anonymous'],
    "setMyCountPreference": ['Function anonymous'],
    "setPushPreference": ['Function anonymous'],
    "startTyping": ['Function anonymous'],
    "unbanUser": ['Function anonymous'],
    "unbanUserWithUserId": ['Function anonymous'],
    "unfreeze": ['Function anonymous'],
    "unmuteUser": ['Function anonymous'],
    "unmuteUserWithUserId": ['Function anonymous'],
    "unreadMentionCount": 0,
    "unreadMessageCount": 0,
    "update": ['Function anonymous'],
    "updateChannel": ['Function anonymous'],
    "updateJoinedMemberCount": ['Function anonymous'],
    "updateReadReceipt": ['Function anonymous'],
    "updateTypingStatus": ['Function anonymous'],
    "url": "clubflora",
}